Fix for ESP32-P4
ESP32-P4 doesn't have usb_common.h header and has the compiler throw an error:

EspUsbHost.h:7:10: fatal error: rom/usb/usb_common.h: No such file or directory

Added a conditional macro to check for header availability and provide the missing defines.